/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SideBySideRouteImport } from './routes/side-by-side'
import { Route as PowderCoatingRouteImport } from './routes/powder-coating'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as JetSkiRepairRouteImport } from './routes/jet-ski-repair'
import { Route as CustomFabricationRouteImport } from './routes/custom-fabrication'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AtvRepairRouteImport } from './routes/atv-repair'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicServiceRequestRouteImport } from './routes/api/public/service-request'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SideBySideRoute = SideBySideRouteImport.update({
  id: '/side-by-side',
  path: '/side-by-side',
  getParentRoute: () => rootRouteImport,
} as any)
const PowderCoatingRoute = PowderCoatingRouteImport.update({
  id: '/powder-coating',
  path: '/powder-coating',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const JetSkiRepairRoute = JetSkiRepairRouteImport.update({
  id: '/jet-ski-repair',
  path: '/jet-ski-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFabricationRoute = CustomFabricationRouteImport.update({
  id: '/custom-fabrication',
  path: '/custom-fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AtvRepairRoute = AtvRepairRouteImport.update({
  id: '/atv-repair',
  path: '/atv-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicServiceRequestRoute = ApiPublicServiceRequestRouteImport.update({
  id: '/api/public/service-request',
  path: '/api/public/service-request',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atv-repair': typeof AtvRepairRoute
  '/contact': typeof ContactRoute
  '/custom-fabrication': typeof CustomFabricationRoute
  '/jet-ski-repair': typeof JetSkiRepairRoute
  '/parts': typeof PartsRoute
  '/powder-coating': typeof PowderCoatingRoute
  '/side-by-side': typeof SideBySideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/service-request': typeof ApiPublicServiceRequestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atv-repair': typeof AtvRepairRoute
  '/contact': typeof ContactRoute
  '/custom-fabrication': typeof CustomFabricationRoute
  '/jet-ski-repair': typeof JetSkiRepairRoute
  '/parts': typeof PartsRoute
  '/powder-coating': typeof PowderCoatingRoute
  '/side-by-side': typeof SideBySideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/service-request': typeof ApiPublicServiceRequestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atv-repair': typeof AtvRepairRoute
  '/contact': typeof ContactRoute
  '/custom-fabrication': typeof CustomFabricationRoute
  '/jet-ski-repair': typeof JetSkiRepairRoute
  '/parts': typeof PartsRoute
  '/powder-coating': typeof PowderCoatingRoute
  '/side-by-side': typeof SideBySideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/service-request': typeof ApiPublicServiceRequestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atv-repair'
    | '/contact'
    | '/custom-fabrication'
    | '/jet-ski-repair'
    | '/parts'
    | '/powder-coating'
    | '/side-by-side'
    | '/sitemap.xml'
    | '/email/unsubscribe'
    | '/api/public/service-request'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atv-repair'
    | '/contact'
    | '/custom-fabrication'
    | '/jet-ski-repair'
    | '/parts'
    | '/powder-coating'
    | '/side-by-side'
    | '/sitemap.xml'
    | '/email/unsubscribe'
    | '/api/public/service-request'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/atv-repair'
    | '/contact'
    | '/custom-fabrication'
    | '/jet-ski-repair'
    | '/parts'
    | '/powder-coating'
    | '/side-by-side'
    | '/sitemap.xml'
    | '/email/unsubscribe'
    | '/api/public/service-request'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtvRepairRoute: typeof AtvRepairRoute
  ContactRoute: typeof ContactRoute
  CustomFabricationRoute: typeof CustomFabricationRoute
  JetSkiRepairRoute: typeof JetSkiRepairRoute
  PartsRoute: typeof PartsRoute
  PowderCoatingRoute: typeof PowderCoatingRoute
  SideBySideRoute: typeof SideBySideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicServiceRequestRoute: typeof ApiPublicServiceRequestRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-by-side': {
      id: '/side-by-side'
      path: '/side-by-side'
      fullPath: '/side-by-side'
      preLoaderRoute: typeof SideBySideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powder-coating': {
      id: '/powder-coating'
      path: '/powder-coating'
      fullPath: '/powder-coating'
      preLoaderRoute: typeof PowderCoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jet-ski-repair': {
      id: '/jet-ski-repair'
      path: '/jet-ski-repair'
      fullPath: '/jet-ski-repair'
      preLoaderRoute: typeof JetSkiRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-fabrication': {
      id: '/custom-fabrication'
      path: '/custom-fabrication'
      fullPath: '/custom-fabrication'
      preLoaderRoute: typeof CustomFabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atv-repair': {
      id: '/atv-repair'
      path: '/atv-repair'
      fullPath: '/atv-repair'
      preLoaderRoute: typeof AtvRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/service-request': {
      id: '/api/public/service-request'
      path: '/api/public/service-request'
      fullPath: '/api/public/service-request'
      preLoaderRoute: typeof ApiPublicServiceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtvRepairRoute: AtvRepairRoute,
  ContactRoute: ContactRoute,
  CustomFabricationRoute: CustomFabricationRoute,
  JetSkiRepairRoute: JetSkiRepairRoute,
  PartsRoute: PartsRoute,
  PowderCoatingRoute: PowderCoatingRoute,
  SideBySideRoute: SideBySideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicServiceRequestRoute: ApiPublicServiceRequestRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
